### ISSUE TITLE
RRULE not included in ICS string

### ISSUE THREAD

**Issue by nehakadam** [outlook/vobject-js#19]
I tried to execute "examples.js" file in vobject-js repo. But I am not able to get RRULE string in ICS string instead I am getting a blank line. I have not modified anything except first line to require vobject.
You can check result on [Tonic](https://tonicdev.com/nehakadam/563223330d81490c00aeaf96).

**Comment by joeydong** [comment]
hi @nehakadam can you try prepending "RRULE:" in front? In your example it should be `event.addRRULE('RRULE:FREQ=DAILY;COUNT=10');`

sorry for the ambiguity

**Comment by nehakadam** [comment]
Hey, Thanks for quick reply. It's working now. But please change it in "examples.js".
