### ISSUE TITLE
request method chaining for setters

### ISSUE THREAD

**Issue by killmenot** [outlook/vobject-js#20]
Hi,

Would it be interesting to add method chaining for set methods? For example, if consider [dateTimeValue](https://github.com/outlook/vobject-js/blob/master/lib/vobject/dateTimeValue.js) it may look the following:
```js
var dateTimeValue = vobject.dateTimeValue();
dateTimeValue.parseTimestamp(timestamp).setTZID(tzid);
```

**Comment by pierre-elie** [comment]
It certainly would! Could you open a pull request?

**Comment by killmenot** [comment]
What style do you prefer to see?

```js
alarm.setAction = function(action) {
  alarm.setProperty(new Property('ACTION', action.toUpperCase()));
  return this;
};
```
or this
```js
alarm.setAction = function(action) {
  alarm.setProperty(new Property('ACTION', action.toUpperCase()));
  return alarm;
};
```

**Comment by pierreliefauche** [comment]
we barely (if at all) use `this` in the current codebase, so I would say style 2

**Comment by pierre-elie** [comment]
We barely (if at all) use `this` in the current codebase, so I would say style 2.
Thanks @killmenot!

**Comment by pierre-elie** [comment]
Published
